version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing - nothing needed for static site"
  build:
    commands:
      - echo "Build started on `date`"
      - echo "No compilation needed for HTML/CSS/JS"
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: '.'
